import{useCallback,useEffect,useRef,useState}from'react';import{Engine,emptyBoard,makeComponent}from'./engine/Engine';import{lessons,allComponents}from'./lessons/lessons';import{key,type Board,type ComponentType}from'./models/types';import{rotateClockwise}from'./utils/direction';import{Palette}from'./components/Palette';import{Grid}from'./components/Grid';import{LessonPanel}from'./components/LessonPanel';import{Inspector}from'./components/Inspector';
const saved=()=>{try{return Number(localStorage.getItem('redstone.lesson'))||0}catch{return 0}};
export function App(){const[index,setIndex]=useState(saved);const[mode,setMode]=useState<'lesson'|'sandbox'>('lesson');const[selectedTool,setTool]=useState<ComponentType|'eraser'>('redstoneDust');const[selected,setSelected]=useState<string>();const[playing,setPlaying]=useState(false);const[debug,setDebug]=useState(false);const[zoom,setZoom]=useState(1);const[,render]=useState(0);const[history,setHistory]=useState<Board[]>([]);const[future,setFuture]=useState<Board[]>([]);const sandbox=useRef<Board>(emptyBoard());const engine=useRef(new Engine(lessons[index].board));const lesson=lessons[index];
 const refresh=()=>render(x=>x+1);const load=useCallback((b:Board)=>{engine.current=new Engine(b);setSelected(undefined);setHistory([]);setFuture([]);refresh()},[]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>{engine.current.tick();refresh()},500);return()=>clearInterval(id)},[playing]);
 useEffect(()=>{localStorage.setItem('redstone.lesson',String(index))},[index]);
 const mutate=(fn:()=>void)=>{setHistory(h=>[...h.slice(-39),structuredClone(engine.current.board)]);setFuture([]);fn();engine.current.settle();refresh();if(mode==='sandbox'){sandbox.current=structuredClone(engine.current.board);localStorage.setItem('redstone.sandbox',JSON.stringify(sandbox.current))}};
 const rotate=()=>{const c=selected&&engine.current.board.cells[selected]?.component;if(c&&'direction'in c)mutate(()=>{c.direction=rotateClockwise(c.direction)})};
 const remove=()=>{if(selected)mutate(()=>delete engine.current.board.cells[selected])};
 useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea'))return;if(e.key===' '){e.preventDefault();setPlaying(p=>!p)}if(e.key.toLowerCase()==='r')rotate();if(e.key==='Delete'||e.key==='Backspace')remove();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)});
 const cellClick=(x:number,y:number)=>{const id=key(x,y),existing=engine.current.board.cells[id]?.component;if(existing){setSelected(id);if(existing.type==='lever'||existing.type==='button')mutate(()=>engine.current.interact(x,y));else if(selectedTool==='eraser')mutate(()=>delete engine.current.board.cells[id]);return}if(selectedTool!=='eraser')mutate(()=>{engine.current.board.cells[id]={x,y,component:makeComponent(selectedTool)};setSelected(id)})};
 const undo=()=>{const last=history.at(-1);if(!last)return;setFuture(f=>[structuredClone(engine.current.board),...f]);setHistory(h=>h.slice(0,-1));engine.current=new Engine(last);refresh()};const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,structuredClone(engine.current.board)]);setFuture(f=>f.slice(1));engine.current=new Engine(next);refresh()};
 const changeLesson=(n:number)=>{setIndex(n);setMode('lesson');load(lessons[n].board)};const toSandbox=()=>{setMode('sandbox');try{sandbox.current=JSON.parse(localStorage.getItem('redstone.sandbox')||'null')||emptyBoard()}catch{sandbox.current=emptyBoard()}load(sandbox.current)};
 const results=lesson.tests.map(t=>t(engine.current.board));const complete=results.every(r=>r.passed);useEffect(()=>{if(complete&&mode==='lesson'){const done=JSON.parse(localStorage.getItem('redstone.completed')||'[]') as string[];if(!done.includes(lesson.id))localStorage.setItem('redstone.completed',JSON.stringify([...done,lesson.id]))}},[complete,lesson.id,mode]);
 return <div className="app">{mode==='lesson'?<LessonPanel lesson={lesson} results={results} index={index} count={lessons.length} completed={complete} onPrevious={()=>changeLesson(index-1)} onNext={()=>changeLesson(index+1)} onSandbox={toSandbox}/>:<header className="sandbox-head"><div><span className="eyebrow">FREE BUILD</span><h1>Sandbox</h1><p>Experiment with every component and inspect hidden circuit state.</p></div><button onClick={()=>changeLesson(index)}>Return to lessons</button></header>}<main><Palette allowed={mode==='lesson'?lesson.allowed:allComponents} selected={selectedTool} onSelect={setTool}/><section className="workspace"><div className="workspace-top"><span>2D CIRCUIT BOARD</span><span className={playing?'running':''}>● {playing?'Running':'Paused'} · Tick {engine.current.tickNumber}</span></div><Grid board={engine.current.board} selected={selected} onCell={cellClick} debug={debug} zoom={zoom}/><div className="controls"><button onClick={()=>setPlaying(p=>!p)}>{playing?'❚❚ Pause':'▶ Play'}</button><button onClick={()=>{engine.current.tick();refresh()}}>Step +1</button><button onClick={()=>load(mode==='lesson'?lesson.board:sandbox.current)}>Reset</button><button onClick={()=>mutate(()=>engine.current.board=emptyBoard())}>Clear</button><button disabled={!history.length} onClick={undo}>Undo</button><button disabled={!future.length} onClick={redo}>Redo</button><i/><button onClick={()=>setZoom(z=>Math.max(.65,z-.1))}>−</button><button onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(z=>Math.min(1.4,z+.1))}>+</button><label><input type="checkbox" checked={debug} onChange={e=>setDebug(e.target.checked)}/> Debug</label></div>{debug&&<div className="debug">Tick {engine.current.tickNumber} · Scheduled events {engine.current.scheduled.length} · Recalculations {engine.current.recalculations} · Update limit {engine.current.unstable?'EXCEEDED':'stable'}</div>}<p className="disclaimer">The simulator models the logical behavior of Minecraft Redstone for learning purposes. It does not guarantee block-for-block compatibility with Minecraft Java or Bedrock Edition.</p></section><Inspector cell={selected?engine.current.board.cells[selected]:undefined} onRotate={rotate} onDelay={n=>{const c=selected&&engine.current.board.cells[selected]?.component;if(c?.type==='repeater')mutate(()=>{c.delay=n})}}/></main></div>}
